title: Denji Xu Homepage
page-top-title: Denji Xu Homepage
top-section-bg-text: Nobody
home-subtitle: Denji Xu
copyright-text: '&copy; Denji Xu 2024. All Rights Reserved. Template by Jerry Yin From <a href="https://github.com/JerryYin777/JerryYin777.github.io">This Repo</a>.'
