title: Denji Xu Homepage
page-top-title: Denji Xu Homepage
top-section-bg-text: Nobody
home-subtitle: Denji Xu
copyright-text: '&copy; Denji Xu 2024. All Rights Reserved. Template by Denji Xu From <a href="https://github.com/liikeuforever/liikeuforever.github.io">This Repo</a>.'
